disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
  - derived
analyzer_rules:
  - explicit_self

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

function_body_length:
  warning: 70
  error: 100
  ignores_comments: true
  ignores_empty_lines: true

line_length:
  warning: 170
  error: 230
  ignores_comments: true
  ignores_function_declarations: true

type_body_length:
  - 400 # warning
  - 500 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4 
  max_length: # warning and error
    warning: 50
    error: 60
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - url
    - XML
    - RCT
    - log
    - Log
    - key
reporter: "xcode"
